# Generated by Django 4.2.2 on 2023-07-01 09:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_record_startplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='startPlace',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
