# Generated by Django 4.2.2 on 2023-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_record_startplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='routeLength',
            field=models.FloatField(),
        ),
    ]
