# Generated by Django 4.2.2 on 2023-07-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_record_routelength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='point',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='routeLength',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
