# Generated by Django 4.2.2 on 2023-07-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_record_point_alter_record_routelength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
