# Generated by Django 4.2.2 on 2023-07-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_record_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='end',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='start',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
