# Generated by Django 4.2.2 on 2023-07-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_record_end_record_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='start',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
